server:
  port: 8000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${MYSQL_HOST}:3306/spring_boot_explore
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
